version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - "/home/yisheng/Documents/monitoring/grafana-storage:/var/lib/grafana"
    restart: always
