version: '3'
services:
  prometheus:
    container_name: prometheus
    network_mode: host
    pid: host
    user: "0"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/log/prometheus:/prometheus
    restart: always
    image: prom/prometheus
